### ISSUE TITLE
Question about render hole in my own data

### ISSUE THREAD

**Issue by Buffyqsf** [spla-tam/SplaTAM#104]
I got a hole in my own captured data as below, I've tried to find out the reason but failed. 
![image](https://github.com/spla-tam/SplaTAM/assets/89965829/2d4ec3f0-3e21-435d-8b35-1e3d0f0289e7)
And I found there is Gaussian, because when I change the view camera's z position, the hole dispeared like below. 
Wondering if you have any experience in such situation.
![image](https://github.com/spla-tam/SplaTAM/assets/89965829/0ceeea8f-758e-4d26-9c84-ff7b8e99f452)

**Comment by Buffyqsf** [comment]
I found there seems to have a crop depth min(near 0.2), but I can't find any code can change this(I've tried to adjust near and far or fov in my view camera)

**Comment by Nik-V9** [comment]
Hi, please refer to this comment: https://github.com/spla-tam/SplaTAM/issues/71#issuecomment-1960921068
