### ISSUE TITLE
Type of Loss Function

### ISSUE THREAD

**Issue by czeyveli1** [spla-tam/SplaTAM#109]
Can I learn what is the type of loss function that used in SplaTAM?

**Comment by Nik-V9** [comment]
Hi, we use both rendered color and depth loss where the losses are weighted using the silhouette when doing tracking.

For details regarding the loss, please refer to the paper or look at this part of the code:
https://github.com/spla-tam/SplaTAM/blob/1a5d407c3a145f69691d49267411cb65e5d5c992/scripts/splatam.py#L214

These slides might also be helpful: http://tinyurl.com/splatam
