### ISSUE TITLE
Question regarding number of frames tracked during SLAM

### ISSUE THREAD

**Issue by ERGOWHO** [spla-tam/SplaTAM#116]
the gt_traj is 2000 for Replica dataset room0, but due to Splatam have the key frame selection, so not all the frames will have a est pose, thus the length of est_traj should be different from gt_traj. If it is right, how did Splatam map due with this issue when evaluating the ATE?

**Comment by Nik-V9** [comment]
Hi, SplaTAM performs keyframe selection only to provide multiple images during the mapping phase.

We run the tracking and mapping at all the frames; hence the length of `est_traj` and `gt_traj` will be equal.
https://github.com/spla-tam/SplaTAM/blob/1a5d407c3a145f69691d49267411cb65e5d5c992/scripts/splatam.py#L643
