### ISSUE TITLE
KeyError: 'ignore_outlier_depth_loss'

### ISSUE THREAD

**Issue by hyunskyu** [spla-tam/SplaTAM#16]
When run with tum dataset, it shows me error like this

-Command
```python
python scripts/splatam.py configs/tum/splatam.py
``` 

-Error
![Screenshot from 2023-12-08 17-58-19](https://github.com/spla-tam/SplaTAM/assets/46669000/0d2d365b-53bd-4a2c-abca-2f27e939cbef)

Maybe missing the keywords in configs/tum/splatam.py

**Comment by Nik-V9** [comment]
Hi, Thanks for testing out the code! This has been fixed now.

**Comment by antonyvan** [comment]
We should also need to add         ignore_outlier_depth_loss=False, 
in tum_eval.py  in  mapping=dict(      
        ignore_outlier_depth_loss=False,
      ...)
