### ISSUE TITLE
Sensor Compatibility & iPhone (ToF) Depth

### ISSUE THREAD

**Issue by darshit-desai** [spla-tam/SplaTAM#18]
Hi Authors,

Awesome paper and algorithm, I was just wondering if the algorithm is able to run with a RGB camera and a ToF sensor. It says in the Readme that it is compatible with the new iphones which has a tof sensor. But I don't have a iphone and I wanted to run it on a drone with tof sensor. What changes would I need to do?

**Comment by Nik-V9** [comment]
Hey, Thanks for your interest in our work!

Yes, it should be possible. Our method currently requires the exact resolution RGB and depth images. The iPhone generally upscales the depth from a ToF sensor using a deep learning model, which we further upscale using nearest interpolation.

For more details, please see:
- https://github.com/apple/ARKitScenes/issues/14
- https://zju3dv.github.io/deltar/
- https://zju3dv.github.io/tof_slam/
- https://zhsun0357.github.io/consistent_dtof_video/

I assume you would need something similar for the RGB and ToF sensor payload on your drone.
