### ISSUE TITLE
Visualisation of SLAM on benchmarking datasets

### ISSUE THREAD

**Issue by darshit-desai** [spla-tam/SplaTAM#20]
Hi Authors, Is there a way to visualize the reconstruction while the slam runs on the benchmarking dataset. I just see a command for running the splatam.py file `python scripts/splatam.py configs/replica/splatam.py` in case of replica dataset. Visualization here refers to the gif of camera tracking and reconstruction which is there in readme

**Comment by JayKarhade** [comment]
Hi @darshit-desai ,

Currently we've provided support for visualization only after the slam is completed. This is through the viz_scripts/ files, and have instructions in the Readme.

However, we do not yet have support for viz while the demo optimization is happening. That is currently in the works. 

See https://github.com/spla-tam/SplaTAM/issues/8#issuecomment-1845351121

**Comment by JayKarhade** [comment]
Closing this for now since we have this as TODO. Feel free to reopen if something is unanswered.
