### ISSUE TITLE
slow evaluation speed

### ISSUE THREAD

**Issue by FrontierBreaker** [spla-tam/SplaTAM#25]
Hi, I find that the training time is very fast but it seems to be stuck during the final evaluation step. Could you please tell me why? Thanks!
Evaluating Final Parameters ...
  7%|██▋                                   | 139/2000 [42:48<7:12:19, 13.94s/it]

**Comment by JayKarhade** [comment]
Is it getting stuck at 139 step or is it slow inference?

The evaluation is slower because we calculate LPIPS and also store images.

**Comment by FrontierBreaker** [comment]
The inference is slow. Is the inference speed normal?

**Comment by Nik-V9** [comment]
Hi, no, this speed is not normal. Generally, the final evaluation is slow since we write the final output for each eval frame to the disk. However, it shouldn't be 7 hr/sequence. This might be an issue with storage on your end?

**Comment by FrontierBreaker** [comment]
okay, I will check it. Thank you!
