### ISSUE TITLE
gradslam_dataconfig.yaml

### ISSUE THREAD

**Issue by lvmingzhe** [spla-tam/SplaTAM#3]
Hi, I want to express my appreciation for the exceptional work you've done. It's truly commendable.

I have a query regarding the availability of a configuration file. Could you kindly provide the configuration file or guide me on how to access it? 

Thank you for your time and assistance.
```
/home/airlab/nkeetha/4d/data/Replica/gradslam_dataconfig.yaml
```

**Comment by Nik-V9** [comment]
Hi, Thanks for trying out the code. This issue has now been fixed. We have updated the config files. You should now have all the resources required to run the code.
