### ISSUE TITLE
Query regarding Ground Truth & 3D Convention

### ISSUE THREAD

**Issue by liaiwanovo** [spla-tam/SplaTAM#31]
Thank you and your team for the excellent code. 

1)  How is the ground truth obtained for your dataset?

2)The generated point cloud is based on what coordinates?

Looking forward to your reply！

**Comment by Nik-V9** [comment]
Hi, Thanks for your queries!
1. We use the ARKit poses as Ground Truth for the iPhone demo.
2. The coordinate system is the first frame (everything is relative to the first frame).

**Comment by liaiwanovo** [comment]
Thank you for your response and excellent work！
