### ISSUE TITLE
RealSense Demo

### ISSUE THREAD

**Issue by IAMHAADICOOL** [spla-tam/SplaTAM#34]
Hey, can you please provide a demo on how to use it with Intel Realsense D435i camera?

**Comment by tingxixue** [comment]
I also encountered this issue. My graphics card is a 4070 Ti, and my FPS is around 0.25.

**Comment by tingxixue** [comment]
Thank you for your question. I also need a demonstration of the D435i video, as transferring images from an iPad through NeRF capture is too slow.

**Comment by darshit-desai** [comment]
Same for me, I also a generic set of instructions to use any stereo camera or RGB-D sensor would be helpful

**Comment by Nik-V9** [comment]
Hi, Thanks for your interest in our work! We will consider this for V2. Please follow this issue thread for updates: https://github.com/spla-tam/SplaTAM/issues/14
