### ISSUE TITLE
open3d 0.17.0 visulization problem

### ISSUE THREAD

**Issue by Buffyqsf** [spla-tam/SplaTAM#43]
I found that when I use open3d=0.17.0, the visualization scripts seems to return a wrong results. The pointclouds is not complete.
I wonder know why and have you tried this before?

**Comment by Nik-V9** [comment]
Hi, Yes, we have observed this issue before: https://github.com/spla-tam/SplaTAM/issues/6

This is a bug with Open3D, where the interactive camera viewer seems to be the cause of the problem.

**Comment by Buffyqsf** [comment]
well thanks very much, I should check the issues more carefully.
