### ISSUE TITLE
recon error

### ISSUE THREAD

**Issue by zhuhu00** [spla-tam/SplaTAM#55]
This is a very good job, and when I was experimenting with the replica dataset, I encountered the following error in the Reconstruction section, but I couldn't find a solution. The open3d==0.16.0 I use. How can I fix it?
```bash
Traceback (most recent call last):
  File "/root/code/viz_scripts/online_recon.py", line 361, in <module>
    visualize(scene_path, viz_cfg)
  File "/root/code/viz_scripts/online_recon.py", line 223, in visualize
    view_control.convert_from_pinhole_camera_parameters(cparams, allow_arbitrary=True)
AttributeError: 'NoneType' object has no attribute 'convert_from_pinhole_camera_parameters'
```

**Comment by xiaoyaocoding** [comment]
I encountered the same issue as you, and it was because I didn't enable remote desktop while running code on the server. After enabling the desktop, the problem was automatically resolved. I hope this helps you.

**Comment by xiaoyaocoding** [comment]
![image](https://github.com/spla-tam/SplaTAM/assets/102663190/50da7166-45c4-447e-82f2-be1ce08c9747)
the difference is I run “python viz_scripts/final_recon.py configs/replica/splatam.py”

**Comment by zhuhu00** [comment]
> ![image](https://private-user-images.githubusercontent.com/102663190/296953022-50da7166-45c4-447e-82f2-be1ce08c9747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODcyODcsIm5iZiI6MTcwNTM4Njk4NywicGF0aCI6Ii8xMDI2NjMxOTAvMjk2OTUzMDIyLTUwZGE3MTY2LTQ1YzQtNDQ3ZS04MmYyLWJlMWNlMDhjOTc0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNjM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWRmZWE0ODE1ZjZhYmY5YzdlYmMxNmQ1YThiNDI0OGVlODc3NWZlZjcwMmEzMzY2MTBlYmM0ZjFmNDU3ZjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuAEpNpAxg8kbbqADCA7-VkmQgPJn6xclSVFO3pKgcg) the difference is I run “python viz_scripts/final_recon.py configs/replica/splatam.py”

Thanks a lot.
