### ISSUE TITLE
How can i get a reconstruction mesh 

### ISSUE THREAD

**Issue by anghaocheng** [spla-tam/SplaTAM#57]
Thank you very much for sharing your excellent work. I got very good rendering results after running the replica dataset, but I did not find the reconstructed 3D mesh. Is there any way  I can get a reconstruction mesh?

**Comment by JayKarhade** [comment]
Hi @anghaocheng , thanks for your interest. 

We current do not support 3D mesh reconstructions from gaussians yet, however you can take a look at some recent work : https://imagine.enpc.fr/~guedona/sugar/

Also i would encourage to take a look at this issue for more details: https://github.com/spla-tam/SplaTAM/issues/33#issuecomment-1869540660

**Comment by Nik-V9** [comment]
Closing this issue since it's similar to #33. Please post updates there.
