### ISSUE TITLE
Question about 'forgetting'

### ISSUE THREAD

**Issue by lif314** [spla-tam/SplaTAM#67]
I noticed that during the training process, some frames are initially optimized very well, with PSNR values exceeding 30. However, when I perform evaluation after the entire map optimization process, the rendering results for the initial frames are not satisfactory. Is there any good way to alleviate this issue? (replica office2 result)

![metrics](https://github.com/spla-tam/SplaTAM/assets/63114150/e6b43c88-94cc-443a-87f9-a804d29f7c10)

**Comment by ljjTYJR** [comment]
I think it is a trade-off between the efficiency and the accuray.
One option might be enlarging the reply buffer;
The other option would be adding some regularization terms to regularize the optimization of Gaussian parameters.

**Comment by Nik-V9** [comment]
I believe that enlarging the mapping window and some updates to our keyframing similar to this paper (https://arxiv.org/abs/2402.03246) should help.

**Comment by AutoSenseTech** [comment]
> I believe that enlarging the mapping window and some updates to our keyframing similar to this paper (https://arxiv.org/abs/2402.03246) should help.

What do you mean by "enlarging the mapping window"? Do you mean changing the parameter `mapping_window_size` in `configs/splatam.py`?
