### ISSUE TITLE
Has this article been accepted by any conference or journal?

### ISSUE THREAD

**Issue by ShilangChen1011** [spla-tam/SplaTAM#83]
Great work! I'm currently writing an article and would like to cite your work. Has this work been formally accepted by any conference or journal?

**Comment by czeyveli1** [comment]
https://arxiv.org/abs/2312.02126

**Comment by JayKarhade** [comment]
Hi! Thanks for your interest in our work! SplaTAM has been accepted and will be presented at CVPR 2024.

**Comment by Nik-V9** [comment]
Readme and other material will be updated shortly to indicate CVPR 2024.
