### ISSUE TITLE
Which configuration file should be used for my own D435 depth camera

### ISSUE THREAD

**Issue by yihuaweiyihua** [spla-tam/SplaTAM#85]
I hope this message finds you. I'm currently working on a project that leverages the Intel D435 depth camera for video capture. Which configuration file in the configs folder should I use. In addition, I would appreciate any advice on how best to organize my data to align with best practices and ensure the highest quality results.

**Comment by Nik-V9** [comment]
Hi, Thanks for your interest!

We don't currently support realsense cameras: https://github.com/spla-tam/SplaTAM/issues/14

We are hoping to support this in our follow-up work.
