### ISSUE TITLE
Stuck on Waiting for frames... when running online iphone_demo.py

### ISSUE THREAD

**Issue by deepankkumar** [spla-tam/SplaTAM#88]
I don't see connections on nerf app. when I run `bash bash_scripts/online_demo.bash configs/iphone/online_demo.py`

I get the following output, and it's stuck at waiting for frames...:

`System Paths:
/home/dksingh/Desktop/SplaTAM/SplaTAM
/home/dksingh/Desktop/SplaTAM/SplaTAM
/home/dksingh/Desktop/SplaTAM/SplaTAM/scripts
/home/dksingh/anaconda3/envs/splatam/lib/python310.zip
/home/dksingh/anaconda3/envs/splatam/lib/python3.10
/home/dksingh/anaconda3/envs/splatam/lib/python3.10/lib-dynload
/home/dksingh/anaconda3/envs/splatam/lib/python3.10/site-packages
Seed set to: 0 (type: <class 'int'>)
1709843454.581087 [0]    python3: config: //CycloneDDS/Domain/Internal/MinimumSocketReceiveBufferSize: setting moved to //CycloneDDS/Domain/Internal/SocketReceiveBufferSize[@min] (CYCLONEDDS_URI+0 line 1)
1709843454.581164 [0]    python3: config: Domain/General/MulticastRecvNetworkInterfaceAddresses/#text: preferred {}
1709843454.581170 [0]    python3: config: Domain/General/ExternalNetworkAddress/#text: auto {}
1709843454.581172 [0]    python3: config: Domain/General/ExternalNetworkMask/#text: 0.0.0.0 {}
1709843454.581175 [0]    python3: config: Domain/General/AllowMulticast/#text: default {}
1709843454.581179 [0]    python3: config: Domain/General/MulticastTimeToLive/#text: 32 {}
1709843454.581182 [0]    python3: config: Domain/General/DontRoute/#text: false {}
1709843454.581185 [0]    python3: config: Domain/General/Transport/#text: udp {}
1709843454.581188 [0]    python3: config: Domain/General/EnableMulticastLoopback/#text: true {}
1709843454.581191 [0]    python3: config: Domain/General/MaxMessageSize/#text: 14720 B {}
1709843454.581194 [0]    python3: config: Domain/General/MaxRexmitMessageSize/#text: 1456 B {}
1709843454.581197 [0]    python3: config: Domain/General/FragmentSize/#text: 1344 B {}
1709843454.581199 [0]    python3: config: Domain/General/RedundantNetworking/#text: false {}
1709843454.581202 [0]    python3: config: Domain/General/EntityAutoNaming/#text: empty {}
1709843454.581206 [0]    python3: config: Domain/General/EntityAutoNaming[@seed]: 1698242773 689435653 4215456180 4122334127 1415414990 1763226872 93300366 267266260 {}
1709843454.581210 [0]    python3: config: Domain/Sizing/ReceiveBufferSize/#text: 1 MiB {}
1709843454.581213 [0]    python3: config: Domain/Sizing/ReceiveBufferChunkSize/#text: 128 KiB {}
1709843454.581216 [0]    python3: config: Domain/Compatibility/StandardsConformance/#text: lax {}
1709843454.581218 [0]    python3: config: Domain/Compatibility/ExplicitlyPublishQosSetToDefault/#text: false {}
1709843454.581222 [0]    python3: config: Domain/Compatibility/ManySocketsMode/#text: single {}
1709843454.581224 [0]    python3: config: Domain/Compatibility/AssumeRtiHasPmdEndpoints/#text: false {}
1709843454.581227 [0]    python3: config: Domain/Discovery/Tag/#text:  {}
1709843454.581229 [0]    python3: config: Domain/Discovery/ExternalDomainId/#text: 0 {}
1709843454.581233 [0]    python3: config: Domain/Discovery/DSGracePeriod/#text: 30 s {}
1709843454.581236 [0]    python3: config: Domain/Discovery/ParticipantIndex/#text: none {}
1709843454.581238 [0]    python3: config: Domain/Discovery/MaxAutoParticipantIndex/#text: 9 {}
1709843454.581245 [0]    python3: config: Domain/Discovery/SPDPMulticastAddress/#text: 239.255.0.1 {}
1709843454.581247 [0]    python3: config: Domain/Discovery/SPDPInterval/#text: 30 s {}
1709843454.581250 [0]    python3: config: Domain/Discovery/DefaultMulticastAddress/#text: auto {}
1709843454.581253 [0]    python3: config: Domain/Discovery/Ports/Base/#text: 7400 {}
1709843454.581256 [0]    python3: config: Domain/Discovery/Ports/DomainGain/#text: 250 {}
1709843454.581258 [0]    python3: config: Domain/Discovery/Ports/ParticipantGain/#text: 2 {}
1709843454.581262 [0]    python3: config: Domain/Discovery/Ports/MulticastMetaOffset/#text: 0 {}
1709843454.581265 [0]    python3: config: Domain/Discovery/Ports/UnicastMetaOffset/#text: 10 {}
1709843454.581269 [0]    python3: config: Domain/Discovery/Ports/MulticastDataOffset/#text: 1 {}
1709843454.581272 [0]    python3: config: Domain/Discovery/Ports/UnicastDataOffset/#text: 11 {}
1709843454.581275 [0]    python3: config: Domain/Discovery/EnableTopicDiscoveryEndpoints/#text: false {}
1709843454.581277 [0]    python3: config: Domain/Discovery/LeaseDuration/#text: 10 s {}
1709843454.581283 [0]    python3: config: Domain/Tracing/Category/#text: fatal,error,warning,info,config {1}
1709843454.581287 [0]    python3: config: Domain/Tracing/OutputFile/#text: stdout {1}
1709843454.581289 [0]    python3: config: Domain/Tracing/AppendToFile/#text: false {}
1709843454.581292 [0]    python3: config: Domain/Tracing/PacketCaptureFile/#text:  {}
1709843454.581294 [0]    python3: config: Domain/Internal/DeliveryQueueMaxSamples/#text: 256 {}
1709843454.581298 [0]    python3: config: Domain/Internal/PrimaryReorderMaxSamples/#text: 128 {}
1709843454.581300 [0]    python3: config: Domain/Internal/SecondaryReorderMaxSamples/#text: 128 {}
1709843454.581303 [0]    python3: config: Domain/Internal/DefragUnreliableMaxSamples/#text: 4 {}
1709843454.581305 [0]    python3: config: Domain/Internal/DefragReliableMaxSamples/#text: 16 {}
1709843454.581308 [0]    python3: config: Domain/Internal/BuiltinEndpointSet/#text: writers {}
1709843454.581311 [0]    python3: config: Domain/Internal/MeasureHbToAckLatency/#text: false {}
1709843454.581314 [0]    python3: config: Domain/Internal/UnicastResponseToSPDPMessages/#text: true {}
1709843454.581316 [0]    python3: config: Domain/Internal/SynchronousDeliveryPriorityThreshold/#text: 0 {}
1709843454.581319 [0]    python3: config: Domain/Internal/SynchronousDeliveryLatencyBound/#text: inf {}
1709843454.581323 [0]    python3: config: Domain/Internal/MaxParticipants/#text: 0 {}
1709843454.581326 [0]    python3: config: Domain/Internal/AccelerateRexmitBlockSize/#text: 0 {}
1709843454.581329 [0]    python3: config: Domain/Internal/RetransmitMerging/#text: never {}
1709843454.581332 [0]    python3: config: Domain/Internal/RetransmitMergingPeriod/#text: 5 ms {}
1709843454.581335 [0]    python3: config: Domain/Internal/HeartbeatInterval/#text: 100 ms {}
1709843454.581338 [0]    python3: config: Domain/Internal/HeartbeatInterval[@min]: 5 ms {}
1709843454.581341 [0]    python3: config: Domain/Internal/HeartbeatInterval[@minsched]: 20 ms {}
1709843454.581343 [0]    python3: config: Domain/Internal/HeartbeatInterval[@max]: 8 s {}
1709843454.581347 [0]    python3: config: Domain/Internal/MaxQueuedRexmitBytes/#text: 512 KiB {}
1709843454.581349 [0]    python3: config: Domain/Internal/MaxQueuedRexmitMessages/#text: 200 {}
1709843454.581352 [0]    python3: config: Domain/Internal/WriterLingerDuration/#text: 1 s {}
1709843454.581355 [0]    python3: config: Domain/Internal/SocketReceiveBufferSize[@min]: 10 MiB {1}
1709843454.581358 [0]    python3: config: Domain/Internal/SocketReceiveBufferSize[@max]: default {}
1709843454.581361 [0]    python3: config: Domain/Internal/SocketSendBufferSize[@min]: 64 KiB {}
1709843454.581364 [0]    python3: config: Domain/Internal/SocketSendBufferSize[@max]: default {}
1709843454.581366 [0]    python3: config: Domain/Internal/NackDelay/#text: 100 ms {}
1709843454.581370 [0]    python3: config: Domain/Internal/AckDelay/#text: 10 ms {}
1709843454.581372 [0]    python3: config: Domain/Internal/AutoReschedNackDelay/#text: 3 s {}
1709843454.581375 [0]    python3: config: Domain/Internal/PreEmptiveAckDelay/#text: 10 ms {}
1709843454.581378 [0]    python3: config: Domain/Internal/ScheduleTimeRounding/#text: 0 s {}
1709843454.581381 [0]    python3: config: Domain/Internal/DDSI2DirectMaxThreads/#text: 1 {}
1709843454.581383 [0]    python3: config: Domain/Internal/SquashParticipants/#text: false {}
1709843454.581386 [0]    python3: config: Domain/Internal/SPDPResponseMaxDelay/#text: 0 s {}
1709843454.581388 [0]    python3: config: Domain/Internal/LateAckMode/#text: false {}
1709843454.581391 [0]    python3: config: Domain/Internal/RetryOnRejectBestEffort/#text: false {}
1709843454.581394 [0]    python3: config: Domain/Internal/GenerateKeyhash/#text: false {}
1709843454.581397 [0]    python3: config: Domain/Internal/MaxSampleSize/#text: 2147483647 B {}
1709843454.581399 [0]    python3: config: Domain/Internal/WriteBatch/#text: false {}
1709843454.581402 [0]    python3: config: Domain/Internal/LivelinessMonitoring/#text: false {}
1709843454.581405 [0]    python3: config: Domain/Internal/LivelinessMonitoring[@StackTraces]: true {}
1709843454.581408 [0]    python3: config: Domain/Internal/LivelinessMonitoring[@Interval]: 1 s {}
1709843454.581410 [0]    python3: config: Domain/Internal/MonitorPort/#text: -1 {}
1709843454.581414 [0]    python3: config: Domain/Internal/PrioritizeRetransmit/#text: true {}
1709843454.581416 [0]    python3: config: Domain/Internal/UseMulticastIfMreqn/#text: 0 {}
1709843454.581419 [0]    python3: config: Domain/Internal/RediscoveryBlacklistDuration/#text: 0 s {}
1709843454.581421 [0]    python3: config: Domain/Internal/RediscoveryBlacklistDuration[@enforce]: false {}
1709843454.581425 [0]    python3: config: Domain/Internal/MultipleReceiveThreads/#text: default {}
1709843454.581427 [0]    python3: config: Domain/Internal/MultipleReceiveThreads[@maxretries]: 4294967295 {}
1709843454.581429 [0]    python3: config: Domain/Internal/Test/XmitLossiness/#text: 0 {}
1709843454.581433 [0]    python3: config: Domain/Internal/Watermarks/WhcLow/#text: 1 KiB {}
1709843454.581435 [0]    python3: config: Domain/Internal/Watermarks/WhcHigh/#text: 500 KiB {}
1709843454.581439 [0]    python3: config: Domain/Internal/Watermarks/WhcHighInit/#text: 30 KiB {}
1709843454.581441 [0]    python3: config: Domain/Internal/Watermarks/WhcAdaptive/#text: true {}
1709843454.581444 [0]    python3: config: Domain/Internal/BurstSize/MaxRexmit/#text: 1 MiB {}
1709843454.581447 [0]    python3: config: Domain/Internal/BurstSize/MaxInitTransmit/#text: 4294967295 {}
1709843454.581450 [0]    python3: config: Domain/Internal/EnableExpensiveChecks/#text:  [ignored] {}
1709843454.581453 [0]    python3: config: Domain/TCP/NoDelay/#text: true {}
1709843454.581455 [0]    python3: config: Domain/TCP/Port/#text: -1 {}
1709843454.581458 [0]    python3: config: Domain/TCP/ReadTimeout/#text: 2 s {}
1709843454.581460 [0]    python3: config: Domain/TCP/WriteTimeout/#text: 2 s {}
1709843454.581464 [0]    python3: config: Domain/TCP/AlwaysUsePeeraddrForUnicast/#text: false {}
1709843454.581466 [0]    python3: config: Domain[@Id]: 0 {1}
1709843454.581481 [0]    python3: started at 1709843454.06581470 -- 2024-03-07 14:30:54-06:00
1709843454.581484 [0]    python3: udp initialized
1709843454.585655 [0]    python3: interfaces: lo udp/127.0.0.1(q1) wls1 wireless udp/192.168.0.100(q9) docker0 udp/172.18.0.1(q9) br-da08685a8fca udp/172.19.0.1(q9)
1709843454.585681 [0]    python3: using network interface wls1 (udp/192.168.0.100) selected arbitrarily from: wls1, docker0, br-da08685a8fca
1709843454.585681 [0]    python3: using network interface wls1 (udp/192.168.0.100) selected arbitrarily from: wls1, docker0, br-da08685a8fca
1709843454.585697 [0]    python3: selected interfaces: wls1 (index 3 priority 0)
1709843454.585704 [0]    python3: presumed flaky multicast, use for SPDP only
1709843454.585724 [0]    python3: ownip: udp/192.168.0.100
1709843454.585731 [0]    python3: extmask: invalid/0 (not applicable)
1709843454.585738 [0]    python3: SPDP MC: udp/239.255.0.1
1709843454.585747 [0]    python3: default MC: udp/239.255.0.1
1709843454.585755 [0]    python3: SSM support included
1709843454.585939 [0]    python3: socket receive buffer size set to 20971520 bytes
1709843454.585958 [0]    python3: rtps_init: uc ports: disc 0 data 0
1709843454.585968 [0]    python3: rtps_init: domainid 0 participantid -2
1709843454.585978 [0]    python3: Unicast Ports: discovery 55929 data 55929
1709843454.586000 [0]    python3: socket receive buffer size set to 20971520 bytes
1709843454.586023 [0]    python3: socket receive buffer size set to 20971520 bytes
1709843454.586035 [0]    python3: Multicast Ports: discovery 7400 data 7401 
1709843454.586054 [0]    python3: socket receive buffer size set to 20971520 bytes
1709843454.586074 [0]    python3: interface wls1: transmit port 40894
Waiting for frames...`

Also, When I run `cyclonedds ps`, I get 0 entities as shown below:
![image](https://github.com/spla-tam/SplaTAM/assets/33066520/e005a891-0b4f-4553-9988-e62dccef12bd)

**Comment by Nik-V9** [comment]
Hi, I would recommend following the discussion here: https://github.com/spla-tam/SplaTAM/issues/2

We have found NeRFCapture to be unreliable. We will have a better custom streaming setup for future releases.
