### ISSUE TITLE
Applicable to Dynamic Avatar Reconstruction?

### ISSUE THREAD

**Issue by Mysterious-handsome-man** [spla-tam/SplaTAM#90]
Impressive work! May I ask if this work can be used for obtaining dynamic 3D facial videos (RGBD video) from monocular video input (RGB video), and using the output RGB and 3D information for facial expression recognition tasks?

**Comment by Nik-V9** [comment]
Hi, Thanks for your interest in our work!

In its current form, SplaTAM only works for static scenes. We might have follow-ups in the future that would work on dynamic monocular videos.

For the application you mentioned, these papers might be relevant (although they require camera poses):
- https://shunsukesaito.github.io/rgca/
- https://animatable-gaussians.github.io/
- https://github.com/MrNeRF/awesome-3D-gaussian-splatting?tab=readme-ov-file#avatars

**Comment by Mysterious-handsome-man** [comment]
Thank you very much for your recommendation! It's very inspiring to me. I will also continue to follow your work!
