### ISSUE TITLE
How to use ground truth camera pose instead of esimating one during reconstruction

### ISSUE THREAD

**Issue by adsf0427** [spla-tam/SplaTAM#96]
If I want to use ground truth camera pose when reconstructing, how can I modify the code splatam.py?

**Comment by Nik-V9** [comment]
Hi, We already support use of ground truth camera pose while doing SLAM.

If you want to use ground truth camera poses while doing SLAM, you can set the following config to `True`:
https://github.com/spla-tam/SplaTAM/blob/8cee05f2ba7e43c8a6f055372a94668867d1fcda/configs/replica/splatam.py#L60

We also support 3D Gaussian Splatting with ground truth camera poses: https://github.com/spla-tam/SplaTAM/blob/main/scripts/gaussian_splatting.py
