### ISSUE TITLE
Aligning 3D Gaussian with Original Point Cloud Coordinates

### ISSUE THREAD

**Issue by adsf0427** [spla-tam/SplaTAM#97]
Description:
Hello, and thank you for the incredible work on this project. I've recently been exploring the use of your codebase for a project where I aim to reconstruct a 3D Gaussian model from a scene and align it with an original point cloud. My goal is to ensure that the 3D Gaussian is properly rotated and aligned with the original point cloud's coordinate system.

Issue Details:

I am unsure about which parameters to adjust in order to rotate the 3D Gaussian model accurately.
My objective is to align the 3D Gaussian with the original point clouds in the same coordinate system.

Questions:

Could you provide guidance  on which parameters should be adjusted for rotating the 3D Gaussian model?
Are there recommended practices or examples for aligning the reconstructed model with the original point clouds' coordinates?

**Comment by Zhaoyibinn** [comment]
Could you please tell me how you solve this problem？
