### ISSUE TITLE
Query regarding Depth Backward Pass (Duplicate)

### ISSUE THREAD

**Issue by adsf0427** [spla-tam/SplaTAM#99]
I've been examining the diff-gaussian-rasterization-w-depth submodule and noticed it explicitly mentions the absence of a backward pass implementation for depth. This limitation implies it cannot be utilized directly for models requiring depth ground-truth during training. However, it occurred to me that in the code the color render interface might serve as an alternative for rendering depth maps in training contexts with depth ground truth. Could you please confirm if utilizing the color render interface in this manner is the intended workaround?

**Comment by Nik-V9** [comment]
Yes, you are right.

Please refer to this message for more details: https://github.com/spla-tam/SplaTAM/issues/54#issuecomment-1887381644
